# Generated by Django 3.2.9 on 2021-11-16 07:45

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20211115_2256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rubric',
            options={'verbose_name': 'Рубрика', 'verbose_name_plural': 'Рубрики'},
        ),
        migrations.AddField(
            model_name='rubric',
            name='description',
            field=models.TextField(default=1, verbose_name='Описание рубрики'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubric',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Отображать на сайте'),
        ),
        migrations.AddField(
            model_name='rubric',
            name='meta_description',
            field=models.TextField(default=1, verbose_name='МЕТА Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubric',
            name='meta_keywords',
            field=models.TextField(default=1, verbose_name='МЕТА Ключевые слова'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubric',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Название рубрики'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubric',
            name='slug',
            field=models.SlugField(default=1, max_length=255, verbose_name='Семантический URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='post',
            name='rubric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.rubric', verbose_name='Рубрика'),
        ),
    ]
