# Generated by Django 3.2.9 on 2021-11-23 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('readers', '0001_initial'),
        ('posts', '0008_alter_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подписки')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='readers.reader', verbose_name='Подписчик')),
                ('rubrics', models.ManyToManyField(related_name='subscriptions', to='posts.Rubric', verbose_name='Рубрики')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
